language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
  - SETTINGS='config.TestConfig'
script:
- source ./environment.sh
- source ./environment_test.sh
- python manage.py db upgrade
- py.test --cov systemofrecord tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: SVOkDnBfcAr/Ok+LhW5msYsLD6cSYe+3C4x3A2Wjr8vhJQ1HW17P+fffWlP28LWuTYodrOJleAQ9B0upOypb5PvbfxHh1lEDO+OK1eZbhhp3JO08seDrYd1kv5e9chsXMD0hfxsZUL54czvy+Yb6V5cFOdMu/d2uXutndg+ohh4=
  strategy: git
  app: lr-system-of-record
  on:
    repo: LandRegistry/system-of-record
    branch: master
    run: "python manage.py db upgrade"
addons:
  postgresql: "9.3"
services:
- redis-server
