from systemofrecord.controllers.load_object_controller import LoadObjectController
from systemofrecord.controllers.store_object_controller import StoreObjectController

load_title_controller = LoadObjectController()
store_title_controller = StoreObjectController()